### ISSUE TITLE
Duplicate glosses

### ISSUE THREAD

**Issue by bulbulistan** [cysouw/pandoc-ling#22]
In some cases (I have found no discernible pattern), a gloss is repeated. For example, the following code

```
:::{.ex formatGloss=true #ilsyn8}
| [BCv3: l-orizzont.63593]
| Kien meta ġie lura li huwa nħatar konsulent tal-Gvern.
| COP.PAST.3SGM when come.PAST.3SGM back COMP 3SGM PASS.select.PAST.3SGM consultant POSS-DEF-government.
| It was when he came back that he was selected to be a goverment consultant.
:::
```
produces the [following HTML](https://i.imgur.com/SejaxIy.png). Note that the DEF is duplicated and the second instance is not smallcap.

Thank you fo your help!

**Comment by cysouw** [comment]
Indeed, there was an error in the regex for the capitalisation. I think I have fixed it. Please try the updated version and tell me if it works for you.

note: I have not yet made a new release with this update: you will have to download the file "pandoc-ling.lua" from the repository itself.

**Comment by bulbulistan** [comment]
Thank you for the quick fix! Unfortunately, the issue still persists. I checked the commit and my suspicion is that there is an extra hyphen in your correction and with the following change, the problem is gone:
```
for leftover in string.gmatch(s, "[%u%d]+([‑%-][^‑%]-[^%u%s]+)$") do
```

**Comment by cysouw** [comment]
argh, Lua patterns are strange... I have uploaded another attempt that should work.

However: please note that you will have to remove the full stop at the end of the glossing line! Full stops have a special meaning in glossing, and it does not make sense to add a full stop at the end of this line. My regex does not capture that full stop, so your example as given at the start of this discussion will not work.

**Comment by bulbulistan** [comment]
I feel ya, I (a Perl/Python/C# person) had to work with Lua once and it was not fun...
Sorry about the full stop, that is my mistake. I tried the new version and it looks all good, thank you so much!
